### ISSUE TITLE
Support decoded Map<String, dynamic> "JSON" input in fromJson

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dart-protobuf#25]
Here's my use-case: I get the JSON for a protobuf inside a larger JSON, so I already have it in decoded (`Map<String, dynamic>`) form.
To deserialize the protobuf with `MyGeneratedMessage.fromJson`, I need to stringify that map first, then let [GeneratedMessage.fromJson](https://github.com/dart-lang/dart-protobuf/blob/master/lib/generated_message.dart#L245) parse it again.

It would be nice to be able to feed the decoded JSON to fromJson.

To do this, I suggest adding the following method to both `GeneratedMessage` and the generated `MyGeneratedMessage`:
`fromDecodedJson(Map<String, dynamic> value, ExtensionRegistry)`.

Any thoughts?

**Comment by skybrian** [comment]
Fixed in 0.3.6. (It's mergeFromJsonMap.)
