### ISSUE TITLE
How about putting clone() into GeneratedMessage?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-protobuf#26]
Protobuf library: Every generate class that extends GeneratedMessage has a clone method, how about putting clone() into GeneratedMessage?
////////////////////////////////////////////////////////////////////////////////////
Editor: 1.5.0.dev_04_02 (2014-06-06)
OS: Windows 8 - amd64 (6.2)
JVM: 1.7.0_51
# projects: 5
# open dart files: 2
auto-run pub: true
localhost resolves to: 127.0.0.1
mem max/total/free: 1778 / 1209 / 552 MB
thread count: 36
index: 1063521 relationships in 180908 keys in 1616 sources

SDK installed: true
Dartium installed: true

**Comment by skybrian** [comment]
Fixed a while ago.
