### ISSUE TITLE
Extension registry is ignored

### ISSUE THREAD

**Issue by sergey-o** [dart-lang/dart-protobuf#27]
The `extensionRegistry` argument in `CodedBufferReader.readGroup` and `CodedBufferReader.readMessage` is ignored.

It looks like
```
message.mergeFromCodedBufferReader(this);
```
 in these methods should be changed to
```
message.mergeFromCodedBufferReader(this, extensionRegistry);
```

**Comment by skybrian** [comment]
Should be fixed as of 0.3.9.
