### ISSUE TITLE
default message created again on each access

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart-protobuf#41]
Code like this has no effect:

    var rec = new pb.Rec();
    rec.msg.str = "hello";

The reason is that when getField() returns the default value of a message field, it doesn't store it in the map. As a workaround, you can explicitly initialize the message:

    var rec = new pb.Rec();
    rec.msg = new pb.Msg();
    rec.msg.str = "hello";

**Comment by tiziano88** [comment]
Note that this breaks Angular2 applications relying on bindings to generated proto messages, as empty messages are not identical in subsequent evaluations and the Change Detector fails loudly thinking that things are changing under its feet.

**Comment by tiziano88** [comment]
I think a possible fix would be to make `getField` cache the return value even in case of generated default values: https://github.com/dart-lang/dart-protobuf/blob/master/lib/src/protobuf/generated_message.dart#L939

**Comment by skybrian** [comment]
I'm thinking that the default value for messages and groups should be null. This will fail cleanly with a NoSuchMethodError if you try to access rec.msg.str without initializing rec.msg.

The alternatives seem trickier. Automatically creating the nested message on first read seems nice at first, but we would have to be careful not to serialize it unless the caller intended that to happen. (Sending an empty message field over the wire has different semantics than not sending a message field at all.) That might be worked around by putting a "touched" flag on each message and setting it on the first mutator call, and only sending touched messages over the wire. But it would be hard to find and fix code that depended on the old behavior.

We will have a change of behavior in any case (breaking backward compatibility), but with a clear error, it will be much easier to find and fix the code that depended on the old behavior.

**Comment by sgjesse** [comment]
I think that this is the right change to do. The current behaviour seems pretty strange providing access to default values through "non-existing" messages.

**Comment by wibling** [comment]
I second skybrian's proposal. Much simpler to reason about.

**Comment by skybrian** [comment]
Here's the current behavior in other languages:

In C++, there are two accessors, foo() and mutable_foo(). If you call foo() then the default message is returned but the result is const,  and the new message is returned without adding it to the parent (has_foo() returns false). If you call mutable_foo() then it's mutable and the new message is added to the parent.

In Java, message types are immutable. getFoo() returns the default message. On a builder, getFooBuilder() returns the builder for the field.

In Go, messages are structs where every field is a pointer. You can access the field directly in which case the default is always nil. Or you can call a getter, which will construct the field's default value if it's nil. It's unclear whether it also adds the value to the struct but from the examples, I suspect not.

In Dart, I think it might be good to add a convenience method for each message or group field, something like:

var msg = new MyMessage();
print(msg.foo); // returns null
msg.ensureFoo()
  ..bar = 1
  ..baz = 2

ensureFoo() should create the default message if necessary and add it to the parent. Otherwise it just returns the existing value of the field.

**Comment by skybrian** [comment]
New proposal:

I looked into converting existing code, and returning null would be significantly worse when reading deep fields. Today you can chain property getters to any depth without worrying about whether the intermediate messages exist:

  var baz = msg.foo.bar.baz;

Instead you would need to manually check if foo is null, and if not create a default instance, and do the same for bar. This is pretty painful when accessing deeply nested fields in an RPC response.

So, I think we need to preserve the ability to use getters in a natural way for field reads. For writes, having an ensure() method pretty much solves the issue:

msg.ensureFoo().ensureBar().baz = 123;

But we still need to report some kind of error if you accidentally write this:

msg.foo.bar.baz = 123;

Also, we need to ensure that identical(msg.foo, msg.foo) is always true.

I think we can solve both problems by giving each message class a factory constructor that returns an immutable instance of its default value:

var msg = new Foo.readonlyDefault();
msg.foo = 123; // throws exception

This could be implemented with a flag that disables all the mutators on the message, or perhaps by returning a subclass that disables setField() and similar methods.

**Comment by tiziano88** [comment]
Thanks Brian for the detailed proposal; I personally disagree with the choice of returning default messages when unset for convenience, even though I am in fact already relying on this behaviour in a few places, especially in Angular2 when I basically assume that everything is already set and I can skip all the null checks. I feel like this kind of "monadic binding" (null pass-through) behaviour should be part of the language itself, rather embedded in every third-party library. In fact, in my opinion it would be great if those getters returned Option types instead of nullable types, but I realise that is a major breaking change at this point, and probably not that convenient for users given the lack of widespread support for Option types in general in Dart. Anyway I'd like to point out that Dart has recently gotten support for a "default" or "null-aware" operators (https://www.dartlang.org/docs/spec/), which is meant to solve this exact issue: you can have nullable fields and not worry about their nullability when chaining accessors; e.g. `var baz = msg?.foo?.bar?.baz` would return `null` if any of the fields in the chain is `null`.

**Comment by skybrian** [comment]
The problem is that when the field isn't present, we want to retrieve its default value, which in general isn't null. So, assuming that the default value of .baz is made available as SomeType.defaultInstance.baz, you'd have to do something like:

var valueOrDefault = msg?.foo?.bar.?baz??SomeType.defaultInstance.baz

That seems rather error-prone; you could return the wrong default if you make a mistake about the type of .bar.

In proto3 this becomes easier because it doesn't support custom defaults for fields, but I expect we'll be supporting proto2 for a while.

**Comment by tiziano88** [comment]
How about storing nulls in the object (and allowing chaining accessors using "null-aware" operators on the fields), and then having additional accessor methods getFoo() (or fooOrDefault() or some variation thereof) that do pretty much what you say? I believe this is very similar if not identical to what Go does (store nulls at the struct-level and provide Get* methods to dereference pointers and fallback to default values), with the difference that Go does not have "null-aware" operators so actually accessing the fields directly can be quite verbose for deeply nested messages.

**Comment by skybrian** [comment]
Update on my proposal: based on a suggestion I'm thinking about having .mutableBar() instead of .ensureBar().

This will fit better when we add more support for immutable messages. The meaning of .mutableBar() is to return the value of .bar, except that if .bar contains a immutable value, replace it with a mutable copy before returning it.

The default instance of a message is an immutable value where all fields are unset and return their default values (recursively). Whenever a field is unset, it should return an immutable default value.

Repeated fields will need to return an immutable, empty list by default. To add something to a repeated field:

msg.mutableFoo().add(...);

**Comment by skybrian** [comment]
Go's approach seems harder to migrate to. I'm not sure our users will like a migration that seems like a downgrade, at least as far as read-only access is concerned.

If you really want a null to indicate "value not present" instead of the field's default value, the expression that works today would be:

msg.hasFoo() ? msg.foo : null;

I'd guess that people want that very often when reading a field, so it doesn't seem worth optimizing for it?

**Comment by skybrian** [comment]
Closing this because the original issue is fixed in 0.4.0.

(It doesn't include adding mutableFoo() fields; for now, you need to use the constructor.)
