### ISSUE TITLE
Strong-mode analysis errors prevent DDC compilation

### ISSUE THREAD

**Issue by ochafik** [dart-lang/dart-protobuf#54]
The following list of [strong-mode](https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md) errors prevent code that depend on `package:protobuf` from being compiled with [DDC](https://github.com/dart-lang/dev_compiler).

(ran ```pub get && dartanalyzer --strong `find lib -name '*.dart'` | sort -u ``` with SDK version `1.16.0-dev.0.0`)

```
[error] Invalid override. The type of PbList.setRange ((int, int, List<E>, [int]) → void) is not a subtype of List<E>.setRange ((int, int, Iterable<E>, [int]) → void). (./lib/src/protobuf/pb_list.dart, line 90, col 3)
[error] Invalid override. The type of PbList.setRange ((int, int, List<E>, [int]) → void) is not a subtype of ListMixin<E>.setRange ((int, int, Iterable<E>, [int]) → void). (./lib/src/protobuf/pb_list.dart, line 90, col 3)
[hint] The method '_getBaseFieldType' is not used (./lib/src/protobuf/generated_message.dart, line 1029, col 7)
[warning] Unsound implicit cast from List<dynamic> to Iterable<GeneratedMessage> (./lib/src/protobuf/builder_info.dart, line 207, col 48)
[warning] Unsound implicit cast from List<dynamic> to Iterable<int> (./lib/src/protobuf/generated_message.dart, line 292, col 29)
[warning] Unsound implicit cast from List<dynamic> to Iterable<int> (./lib/src/protobuf/generated_message.dart, line 378, col 27)
[warning] Unsound implicit cast from List<dynamic> to Iterable<int> (./lib/src/protobuf/generated_message.dart, line 678, col 27)
[warning] Unsound implicit cast from List<dynamic> to Iterable<int> (./lib/src/protobuf/generated_message.dart, line 708, col 27)
[warning] Unsound implicit cast from List<dynamic> to Iterable<int> (./lib/src/protobuf/unknown_field_set.dart, line 137, col 21)
[warning] Unsound implicit cast from dynamic to List<int> (./lib/src/protobuf/generated_message.dart, line 654, col 42)
[warning] Unsound implicit cast from dynamic to Map<String, dynamic> (./lib/src/protobuf/generated_message.dart, line 844, col 20)
```

**Comment by emesx** [comment]
This should be easy to fix.
I'm using `1.16.0-dev.1.0` though, and the output is different already e.g. TODOs are treated as errors.

Anyways, expect a PR soon.

**Comment by ochafik** [comment]
@skybrian Is the "TODOs treated as errors" a known issue btw?

**Comment by skybrian** [comment]
It's not known to me. TODO's started being reported recently but the severity shouldn't be 'error'. That part sounds like a bug.

**Comment by ochafik** [comment]
@skybrian re/ TODOs, filed https://github.com/dart-lang/sdk/issues/26026

**Comment by skybrian** [comment]
I created .analysis_options with strong mode enabled, applied the patch, and I'm still getting a bunch of errors. Here's one of them:

Unsound implicit cast from List<dynamic> to Iterable<int>lib/src/protobuf/json.dart, line 62
The code looks like this:

```
for (int tagNumber in sorted(fs._extensions._tagNumbers)) {
```

It appears that the generics comments added to the "sorted" method don't actually fix the error:

```
List/*<T>*/ sorted/*<T>*/(Iterable/*<T>*/ list) => new List.from(list)..sort();
```

Here's the definition of _tagNumbers:
Iterable<int> get _tagNumbers => _values.keys;

This is with 1.16.0-edge something. I'll try rebuilding my SDK directory - it might be stale.

**Comment by ochafik** [comment]
Seems properly fixed when testing in command-line (tested `1.16.0-dev.0.0` and `1.16.0-dev.2.0`), @skybrian please let me know if the issues you mentioned still creep up!

**Comment by skybrian** [comment]
We aren't actually done yet. The warnings may be gone, but the protobuf library needs to be adjusted to that generated code will work with DDC. See: https://codereview.chromium.org/1829573002/

**Comment by skybrian** [comment]
re: "Seems properly fixed when testing in command-line (tested 1.16.0-dev.0.0 and 1.16.0-dev.2.0)"

Do you have a way of testing in strong mode? If so I'd like to know how to do it.

**Comment by ochafik** [comment]
@skybrian I just used the same command line as in the bug description (after a `pub get` of course). Now just getting a deprecation hint about 'CryptoUtils'. Is there any good example of generated code, to run the analyzer on it?

**Comment by skybrian** [comment]
I misunderstood; I thought maybe there was a way to run the tests in DDC. (I already know how to run the analyzer.)

There are tests and example code in dart-protoc-plugin. I have a CL in review [1] to fix everything that I'll probably land on Monday.

[1] https://codereview.chromium.org/1829573002/

**Comment by ochafik** [comment]
Ah, sorry! Not sure about running tests in DDC, as it doesn't support VM libs (dart:io, etc, not sure if they're needed by package:test?), @vsmenon anyn idea / plans about that?

**Comment by skybrian** [comment]
All the open source changes are committed. Working on a release.

**Comment by ochafik** [comment]
Awesome, thanks @skybrian and @emesx !!!
