### ISSUE TITLE
Incorrect results decoding ZigZag for int32 using Dart2js

### ISSUE THREAD

**Issue by jkramber** [dart-lang/dart-protobuf#59]
The decoding worked in Dartium, but when I used Dart2js deserializing a protocol buffer containing signed int32s it threw exceptions for values being out of bounds of signed int32. 

Fox32 found the replacement function that works, I have tested and confirmed that it works in Dartium and in Chrome with Dart2js.

http://stackoverflow.com/questions/17427976/bitwise-operations-wrong-result-in-dart2js/17433485#17433485

Can this function replace the _decodeZigZag32 in coded_buffer_reader.dart or will users need to account for this issue themselves?

**Comment by skybrian** [comment]
Should be fixed in 0.5.3.
