### ISSUE TITLE
support Windows

### ISSUE THREAD

**Issue by czlbaiyi** [dart-lang/dart-protobuf#64]
i want use protobuf on windows,but now it only suport unix ? has the plan to suport windows?

**Comment by skybrian** [comment]
The protobuf library should work, but it is not useful by itself. To generate the code you need to use dart-protoc-plugin and there is currently no easy way to use it on Windows. Perhaps someone who uses Windows can figure it out?

**Comment by czlbaiyi** [comment]
@skybrian  thanks to report this。
now I has use dart-protoc-plugin to  generate the code at mac os。then I  well use it at windows。
